### ISSUE TITLE
integração com repo privado

### ISSUE THREAD

**Issue by saramortara** [covid19br/nowcasting#1]
repo privado precisa enviar os arquivos para o diretório: dados/outputs_nowcasting/[escala]_[sigla]. p.ex: `dados/outputs_nowcasting/municipio_SP`, `dados/outputs_nowcasting/estado_PE`

**Comment by AndreaSanchezTapia** [comment]
Fiz um teste aqui para municipio_SP e parece ok. só nao enviei rds. Deixei um pre-robô lá para ver se dá para fazer funcionar. Affe já vi o primeiro erro, deixei dados/municipio_SP, não criei "outputs_nowcasting" no path.

**Comment by saramortara** [comment]
eu movi os outputs para o local que deveria ir. Agora precisa consertar o robô para mandar para o local certo
