### ISSUE TITLE
mover pastas dados_processados e docs pro repo central_covid

### ISSUE THREAD

**Issue by renatocoutinho** [covid19br/nowcasting#13]
Conforme discutido na reunião de 26/05, é melhor o repo nowcasting ser mais "só o pacote", e os outputs gerados ficarem em pastas do meta-repo.

* [x] mover os arquivos
* [x] trocar os caminhos default dos scripts update_*.R
* [x] não esquecer de colocar os arquivos `*_post_*.csv`  no .gitignore do meta-repo

**Comment by AndreaSanchezTapia** [comment]
tirei o nowcasting/ (folder) do gitignore mas precisa voltar -estava interferindo com o padrão de ignore dos arquivos post.

**Comment by renatocoutinho** [comment]
é só usar "/nowcasting" no .gitignore, ele trata / como caminho relativo à raiz, e aí nowcasting é uma pasta específica e não um pattern. Aliás, isso devia ser feito pra /site também

**Comment by renatocoutinho** [comment]
corrigi isso já
