### ISSUE TITLE
update_nowcasting com plot e gitUpdate TRUE não adiciona plots/data_*.csv

### ISSUE THREAD

**Issue by renatocoutinho** [covid19br/nowcasting#14]

**Comment by AndreaSanchezTapia** [comment]
foi com um simples list.files sem pattern

**Comment by renatocoutinho** [comment]
Não faz isso, não, a chance de dar bobagem aumenta muito! Tem a lista de arquivos em algum lugar - os plots são filenames[plots.true], os nomes das tabelas são bem previsíveis também, dá pra montar no _src/04
