### ISSUE TITLE
investigar por que alguns plots saem com range x menor

### ISSUE THREAD

**Issue by renatocoutinho** [covid19br/nowcasting#15]
vários exemplos em `dados/estado_SP/SRAG_hospitalizados/reports/relatorio_2020_05_27.html`, em especial de Campinas, que tem um plot só com 2 pontos. Numa primeira olhada me parece que não é o código de plotting, precisa investigar os dados também.

Provavelmente relacionada à #12

**Comment by AndreaSanchezTapia** [comment]
Botei uma cláusula lógica de só cortar se antes de 15/03/2020 já tem casos suficientes, mas se não tiver não corta. Eventualmente esta data pode ser um argumento e ter outro valor, podemos pedir para mostrar as últimas duas semanas, por exemplo, não precisa ser desde 15 de março. Não sei se estou esquecendo de algo. Não vou fechar ainda...

**Comment by renatocoutinho** [comment]
Parece tudo OK, faz tempo que não vejo nada ruim, fechando
