### ISSUE TITLE
Erro de arredondamento? No momento o R_e está entre 1 e 1.

### ISSUE THREAD

**Issue by francocarol** [covid19br/nowcasting#17]
Se o valor de R_e está sendo arredondado, poderíamos adicionar 1 ou 2 dígitos aós a vírgula, para a frase fazer sentido.

**Comment by AndreaSanchezTapia** [comment]
Tem algum problema de o número ser igual, mesmo com duas casas decimais? ou vocês acham que fica melhor comunicar o intervalo com um intervalo mesmo (um floor e um ceiling?)

**Comment by AndreaSanchezTapia** [comment]
era uma besteira de formatação de vetor ou fator, nem sequer era de arredondamento. mas ficou com duas casas caso tenha pouca diferença.

**Comment by renatocoutinho** [comment]
agora foi! Atualizei todas as tabelas do site já
