### ISSUE TITLE
As estimativas são sempre número inteiros?

### ISSUE THREAD

**Issue by vsudbrack** [covid19br/nowcasting#22]
Porque as estimativas são sempre números inteiros?
Em cidades com poucos casos o arredondamento pode provocar alterações importantes..

**Comment by renatocoutinho** [comment]
Porque as trajetórias são geradas a partir de distribuições de probabilidades discretas (Poisson), e o que aparece no site são quantis dessas trajetórias (mediana e quantis 2,5 e 97,5%), que em geral são inteiros também.
