### ISSUE TITLE
Divulgar distribuição de atrasos

### ISSUE THREAD

**Issue by vsudbrack** [covid19br/nowcasting#23]
Que tal uma aba com a distribuição de atrasos acumulativa para cada cidade?
Isso dá uma boa noção da qualidade da gestão de testagem de cada município, e pode nos ajudar a entender alguns nowcasting aparentemente "exagerados".

**Comment by renatocoutinho** [comment]
Tem código para calcular, mas não é prioridade divulgar no site.
