### ISSUE TITLE
implementar filtro de residentes para estados em `read.sivep`

### ISSUE THREAD

**Issue by renatocoutinho** [covid19br/nowcasting#25]
É a única escala que não usa isso - usa `sg_uf` que (acho que) é a sigla do estado de notificação.

**Comment by rafalopespx** [comment]
`sg_uf` é a unidade da federação de residência do paciente, por padrão pegamos a `sg_uf` correta, de residência, para `sg_uf_not`pega a unidade da federação de notificação

Precisaria criar a opção de varia isso em `read.sivep`
