### ISSUE TITLE
nowcasting semanal

### ISSUE THREAD

**Issue by renatocoutinho** [covid19br/nowcasting#34]
Vamos fazer nowcasting semanal.

- [x] gerar nowcasting semanal, inclusive posteriores (PI)
- [X] dar merge no branch betas_nowcasting
- [X] criar branch dev
- [x] implementar opção "semanal" na linha de comando do `update_nowcasting` (Andrea)
- [x] implementar interpolação diária pra calcular Reff (Renato)
- [x] verificar se resultado do Reff faz sentido (Renato)
- [x] transformar datas de saída do Reff pra semanal (Renato)
- [x] corrigir chamada de `now.proj` e/ou `forecast_exponential` para lidar com dados semanais
- [x] testar se plots e exportação de dados pro site funcionam (Sara)
- [ ] tabelas para gráficos precisam mostrar dados por dia (ver item abaixo) (Sara)
- [x] revisar explicações do site inteiro! Mudar explicação: número de casos/dia na semana
- [x] dar merge do dev pro master
- [x] desativar cálculo de tempo de duplicação quando semanal = TRUE?

**Comment by AndreaSanchezTapia** [comment]
- [x] média móvel agora tá smooth demais, testar com ~4

**Comment by renatocoutinho** [comment]
Erros do nowcasting semanal: 

1. erro mais comum (14/20 com base SP 2020_11_18). Ex: DRS Araraquara, município Diadema

```
Computing a nowcast for  2020-11-15
`summarise()` ungrouping output (override with `.groups` argument)
No id variables; using all as measure variables
Error in seq.int(0, to0 - from, by) : 'to' must be a finite number
Calls: source ... gera.nowcasting -> NobBS -> <Anonymous> -> nth -> seq -> seq.Date

```

Possíveis warnings relacionados:

```
5: In max.default(numeric(0), na.rm = FALSE) :
  no non-missing arguments to max; returning -Inf
6: In max.default(c(NA_real_, NA_real_, NA_real_, NA_real_, NA_real_,  :
  no non-missing arguments to max; returning -Inf
```
Parece ter sido corrigido no 04106478e11 (a ser melhor testado)

**Comment by renatocoutinho** [comment]
2. Erro menos comum (6/20 com base SP 2020_11_18). Ex: DRS Presidente Prudente, município Jundiaí

```
Computing a nowcast for  2020-11-15
`summarise()` ungrouping output (override with `.groups` argument)
No id variables; using all as measure variables
Computing a nowcast for  2020-10-11
`summarise()` ungrouping output (override with `.groups` argument)
Error in names(coredata(x)) <- value : 
  'names' attribute [1] must be the same length as the vector [0]
Calls: source ... $<- -> $<-.zoo -> setNames -> names<- -> names<-.zoo
```
Aparentemente acontece depois do nowcasting só (tem a ver com objetos zoo). Possíveis warnings relacionados:

```
2: In max.default(numeric(0), na.rm = FALSE) :
  no non-missing arguments to max; returning -Inf
5: In min.default(numeric(0), na.rm = TRUE) :
  no non-missing arguments to min; returning Inf
```
Parece ter sido corrigido no 0410647 também (era relacionado ao outro erro, mas dava problema em outro lugar?)

**Comment by renatocoutinho** [comment]
- [X] R efetivo da cidade e estado de SP tem um pico muito bizarro que não parece corresponder à curva de casos.

**Comment by renatocoutinho** [comment]
- [ ] desativar cálculo de tempo de duplicação quando semanal = TRUE?

**Comment by renatocoutinho** [comment]
- [x] comparar valores de R (especialmente barras de erro) usando o nowcasting semanal com os valores antigos

**Comment by piklprado** [comment]
![r_efetivo_diarios_semanal_met_novo_srag_campinas](https://user-images.githubusercontent.com/6313365/100395945-cb6e7580-3021-11eb-92da-575c59fe1441.png)

R efetivo de SRAG em Campinas, calculado com nowcasting diário (azul) e semanal (vermelho). Arrasou, data team detetizaram todos os bugs!

---
Os comandos que dei a partir do diretorio nowcasting , para obter as tabelas de onde fiz os plots (balaio é um dir que tenho pra jogar coisas aleatórias):

```
Rscript update_nowcasting.R --escala municipio --geocode 3509502 --escala municipio --dir ../dados/SIVEP-Gripe --outputDir ../balaio/Cori --window 10 --trim 0 --semanal TRUE --Rmethod Cori

Rscript update_nowcasting.R --escala municipio --geocode 3509502 --escala municipio --dir ../dados/SIVEP-Gripe --outputDir ../balaio/Cori_diario --window 40 --trim 5  --Rmethod Cori
```

E aqui para município de São Paulo, SRAG tb:

![r_efetivo_diarios_semanal_met_novo_srag_sampa](https://user-images.githubusercontent.com/6313365/100400821-8274ec00-3036-11eb-8b23-fa38a21da11b.png)

**Comment by piklprado** [comment]
> * [x]  média móvel agora tá smooth demais, testar com ~4

Que acham de tirar média móvel dos plots de  nowcasting semanal?

**Comment by piklprado** [comment]
> * [ ]  desativar cálculo de tempo de duplicação quando semanal = TRUE?

Total acordo. Aliás, desativar de tudo? Ou ainda precisamos de tempo de duplicação para algo?

**Comment by piklprado** [comment]
> tabelas para gráficos precisam mostrar dados por dia (ver item abaixo) (Sara)

Não achei este item, o que é isso @saramortara ?

**Comment by renatocoutinho** [comment]
> > * [ ]   desativar cálculo de tempo de duplicação quando semanal = TRUE?
> 
> Total acordo. Aliás, desativar de tudo? Ou ainda precisamos de tempo de duplicação para algo?

Acho que não usamos mais, mas alguém ainda olhava de vez em quando pra fazer comparações. Entra na caixinha "legacy", mas realmente não tem sentido no caso semanal.

**Comment by renatocoutinho** [comment]
> > tabelas para gráficos precisam mostrar dados por dia (ver item abaixo) (Sara)
> 
> Não achei este item, o que é isso @saramortara ?

Isto tem a ver com aquela história de ainda manter um output de dados diários, você tinha cogitado de adicionar uma aba mais tarde, mas talvez só uma tabela resolva. De qualquer forma, fica pra v2.

**Comment by piklprado** [comment]
Recife deu ruim, o que pode ter acontecido?
SRAG:
![r_efetivo_diarios_semanal_met_novo_srag_recife](https://user-images.githubusercontent.com/6313365/100405202-e355f180-3041-11eb-8ec6-2d83fcbe0ddd.png)

E para covid tb:
![r_efetivo_diarios_semanal_met_novo_covid_recife](https://user-images.githubusercontent.com/6313365/100405242-f5379480-3041-11eb-9209-2d2f2cd156b7.png)

**Comment by piklprado** [comment]
Mais algumas verificações. So far, so good

## Curitiba
### SRAG
![r_efetivo_diarios_semanal_met_novo_srag_curitiba](https://user-images.githubusercontent.com/6313365/100413363-e8bd3700-3055-11eb-8a01-dde7464b8d11.png)

### Covid
![r_efetivo_diarios_semanal_met_novo_covid_curitiba](https://user-images.githubusercontent.com/6313365/100413364-e955cd80-3055-11eb-924a-839bd0130f7c.png)

## Palmas
### SRAG
![r_efetivo_diarios_semanal_met_novo_srag_palmas](https://user-images.githubusercontent.com/6313365/100413404-038fab80-3056-11eb-8e64-74e7bf956671.png)

### COVID
![r_efetivo_diarios_semanal_met_novo_covid_palmas](https://user-images.githubusercontent.com/6313365/100413408-04284200-3056-11eb-863f-8b83a090aacd.png)

## Recife
### SRAG
![r_efetivo_diarios_semanal_met_novo_srag_recife](https://user-images.githubusercontent.com/6313365/100413410-04284200-3056-11eb-9966-59b1acf29c1f.png)
### COVID
![r_efetivo_diarios_semanal_met_novo_covid_recife](https://user-images.githubusercontent.com/6313365/100413411-04c0d880-3056-11eb-8646-1b5dfa3810d8.png)

**Comment by AndreaSanchezTapia** [comment]
Vamos deixar o assunto das tabelas diárias em uma issue nova
