### ISSUE TITLE
todos plots SRAG devem começar 15/03

### ISSUE THREAD

**Issue by renatocoutinho** [covid19br/nowcasting#4]
Conferi no município_SP e só falta corrigir o plot de R efetivo (plot_estimate_R0_srag). É bom checar se isso é feito de maneira geral, não só pra município SP.

**Comment by renatocoutinho** [comment]
Corrigido no repo site, mas precisa levar isso em conta nos plots do nowcasting também.

**Comment by AndreaSanchezTapia** [comment]
Esta parte específica está OK, nada começa antes de 15/03 então vou fechar esta.
