### ISSUE TITLE
nowcasting para database passada

### ISSUE THREAD

**Issue by AndreaSanchezTapia** [covid19br/nowcasting#6]
Gerei o output para 11/05 para checar o efeito do corte de datas desde 15/03 para srag (quero comparar com as mesmas tabelas que estão no site). Estou percebendo que o nowcasting foi até o presente e a projeção até dia 24 como se desconsiderasse a data base.

**Comment by saramortara** [comment]
acho que o ponto aqui é discutir onde a gente tem que fazer o corte. Eu tinha colocado em `01-b_analises_nowcasting.R` assumindo `dia.zero.srag <- "2020-03-15"` depois de já ter feito todas as análises e estimativas. Mas isso está gerando algo estranho.

**Comment by AndreaSanchezTapia** [comment]
mas o nowcasting vir até o presente também precisamos checar

**Comment by AndreaSanchezTapia** [comment]
Resolvido - não era o corte mas um Sys.data() em now.proj(). A mudança na data de corte não muda em nada o output.
